source "https://supermarket.getchef.com"
source 'https://supermarket.chef.io'

cookbook 'nodeworks_opsworks', path: 'nodeworks_opsworks'

cookbook 'chef_nginx'
cookbook 'chef_slack'
cookbook 'application_git'
cookbook 'certbot'
cookbook 'php-fpm'